### ISSUE TITLE
New macOS errors at CRAN

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/nanotime#128]
Following the 0.3.8 we now see [results](https://cloud.r-project.org/web/checks/check_results_nanotime.html) with errors on macOS arm64:

```
  ----- FAILED[data]: test_nanotime.R<143--143>
   call| expect_identical(p, as.POSIXct(as.nanotime(p)))
   diff| Attributes differ
  ----- FAILED[data]: test_nanotime.R<147--147>
   call| expect_identical(p, as.POSIXct(as.nanotime(p)))
   diff| Attributes differ
  Error: 2 out of 1250 tests failed
  Execution halted
```

We know arm64 has less precision that x86_64 but could something else be going on?  The code is

https://github.com/eddelbuettel/nanotime/blob/aadc9182d0749f08ca745605011a99f5e1e8c2d0/inst/tinytest/test_nanotime.R#L139-L147

and the reference in the comment to #115 is a hint as #116 may play a role here.

@davorj @lsilvest Any thoughts?   Would `accurate=FALSE` help?  

PS I guess not.  The next test asserts that.  So ... should we skip these two tests on arm64?

**Comment by DavorJ** [comment]
> ```
>    call| expect_identical(p, as.POSIXct(as.nanotime(p)))
>    diff| Attributes differ
> ```

Hi @eddelbuettel. I don't have an ARM system to test, but the difference seems to be the attribute, not the `double` itself? 

Printing `dput(p)` should show the attributes, and `sprintf("%a", p)` the binary representation of the `double`. This would allow better comparison.

Disabling this test or ARM is OK, or even disallowing it as you suggest in #129, if urgent. But a real solution would require some debugging.

**Comment by eddelbuettel** [comment]
I do not have arm64 access either besides the ones _everybody_ has access to namely
- the macOS-latest runners here (which switched a few weeks ago from x86_64 to arm64)
- the [macOS builder](https://mac.r-project.org/macbuilder/submit.html) machine provided by Simon Urbanek on behalt of the R team

If you have debugging ideas, can  you try either?   I may put out a stop-gap release as per this PR sooner rather than later, we should then have time for a deeper look.

**Comment by DavorJ** [comment]
### From Win11 ARM64 VM with R4.4.1 and `nanotime_0.3.8`:

![image](https://github.com/eddelbuettel/nanotime/assets/4161918/3c039b56-aff0-4941-87c3-a7a5befd5a63)

And second one:

![image](https://github.com/eddelbuettel/nanotime/assets/4161918/d478620d-d128-4274-b8c9-d0f864cbf694)

### From Win11 x64 with R4.1.3 and `nanotime_0.3.8`:

![image](https://github.com/eddelbuettel/nanotime/assets/4161918/863e3f98-82bc-4f32-8587-89404be2499b)

And second one:

![image](https://github.com/eddelbuettel/nanotime/assets/4161918/d9d44a38-2e92-4c12-b4db-2d3e70ea0048)

So it seems the POSIXct -> nanotime -> POSIXct consistency idea doesn't hold on ARM systems, indeed...

**Comment by eddelbuettel** [comment]
Hm, I thought it was known that arm64 has slightly less double precision but now I cannot find a good reference to bag this up.  But maybe _some_ operations are different?  Can you maybe run a series over powers of then similar to the following I something use to where the 'delta' between two POSIXct is no longer noticeable?

```r
> now <- Sys.time(); for (i in seq(-1,-8,by=-1)) cat("As 10^", i, " can see difference: ", now + 10^i != now, "\n", sep="")
As 10^-1 can see difference: TRUE
As 10^-2 can see difference: TRUE
As 10^-3 can see difference: TRUE
As 10^-4 can see difference: TRUE
As 10^-5 can see difference: TRUE
As 10^-6 can see difference: TRUE
As 10^-7 can see difference: FALSE
As 10^-8 can see difference: FALSE
> 
```

(Also, if I may, copy and pasting _code_ rather than screenshots is much preferred.)

**Comment by DavorJ** [comment]
From Win11 ARM64:

```r
> now <- Sys.time()
> for (i in seq(-1,-8,by=-1)) cat("As 10^", i, " can see difference: ", now + 10^i != now, "\n", sep="")
As 10^-1 can see difference: TRUE
As 10^-2 can see difference: TRUE
As 10^-3 can see difference: TRUE
As 10^-4 can see difference: TRUE
As 10^-5 can see difference: TRUE
As 10^-6 can see difference: TRUE
As 10^-7 can see difference: FALSE
As 10^-8 can see difference: FALSE
```

(Sorry for screenshots: had some copy/paste RDP issues.)

**Comment by DavorJ** [comment]
Why would ARM64 have any less precision? Eventually it is just bits and conformance to standards. See [here](https://stackoverflow.com/a/64041506/1548942) for example.

**Comment by eddelbuettel** [comment]
I am sorry, I am a little busy and was brief. I was not asking you to re-run the example I used to 'see' the minimally supported diff on POSIXct.

You were the one introducing the round-robin on the 'unusual' character string. My thinking was that maybe you construct a similar test for arm64 to determine up to which precision we can possible round-turn.

(We do *not* in general have control over "unusual" compiler switches. CRAN barks when you use one they consider non-portable, see release notes for this 0.3.8 release for an example.)

**Comment by DavorJ** [comment]
On x64 systems, the round robin works 100 % (except on very small numbers where double x 1E9 has a fraction and cannot be stored within the 64bit integer, and same with doubles exceeding the 64bit integer boundaries). That the round-robin works 100 % within these bounds I tested [here](https://github.com/eddelbuettel/nanotime/issues/115#issuecomment-1575504163).

On ARM64, if this round-robin doesn't hold for `2023-06-04 10:12:35.250385 UTC` which is `1685873555.2503853`, then why expect it to work consistently on any current date? And even if there was a valid range, it would be a 15-16 digit integer corresponding to dates almost no-one cares about.

Hence for now disabling the test and even `accurate = TRUE` (since it clearly isn't accurate) on ARM64 seems completely logical to me.

Note also that I tried my original implementation too ([here ](https://github.com/eddelbuettel/nanotime/issues/115#issuecomment-1575504163) and [here](https://github.com/eddelbuettel/nanotime/issues/115#issuecomment-1575480385)), and I got the same discrepancy.

**Comment by eddelbuettel** [comment]
Well two (or three) things:

- the new 'accurrate' flag and this test came after 0.3.7, and were never at CRAN so no arm64 there
- plus I am usually impatient and only run Linux CI so macOS was off 
- *but* GH did us all a favor and swicthed from x86_64 macOS to arm64 macOS a few months ago

And as we did not have arm64 'on' we did not see this.  So that one is on me, but it will be quick to address.  The PR is out there, I plan to roll that up tomorrow morning.

**Comment by lsilvest** [comment]
OK, that makes sense then. Still a little curious about the error message mentioning "attributes"...On Jun 21, 2024, at 00:27, Dirk Eddelbuettel ***@***.***> wrote:﻿
Well two (or three) things:

the new 'accurrate' flag and this test came after 0.3.7, and were never at CRAN so no arm64 there
plus I am usually impatient and only run Linux CI so macOS was off
but GH did us all a favor and swicthed from x86_64 macOS to arm64 macOS a few months ago

And as we did not have arm64 'on' we did not see this.  So that one is on me, but it will be quick to address.  The PR is out there, I plan to roll that up tomorrow morning.

**Comment by eddelbuettel** [comment]
Yeah the nature of the error message is also weird to me.  

I was just out biking for a bit but overnight we also got the auto-nag:

> Dear maintainer,
>
> Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_nanotime.html>.
>
> Please correct before 2024-07-05 to safely retain your package on CRAN.
>
> The CRAN Team

I will take care of it now.

**Comment by eddelbuettel** [comment]
Dealt with in #129
