### ISSUE TITLE
nanotime and ggplot2?

### ISSUE THREAD

**Issue by randomgambit** [eddelbuettel/nanotime#21]
Hi @eddelbuettel, thanks for this amazing package! 

Nanotime support is clearly what we need at the moment. I am wondering if your package is compatible with `ggplot2`. 

Can I create charts that have an x-axis with timestamps up to nanoseconds? Are there any particular issues?

Thanks!

**Comment by eddelbuettel** [comment]
Sure.  You will need to write a custom format routine to do that.   For POSIXct we get this for free because R natively supports, for extensions we have to do it by hand (and eventually integrate it).   This is no different for nanotime than it is for other time package such as chron which are not using POSIXct.  Or for packages extending POSIXct such as xts -- you could start by looking at plot.xts.

**Comment by randomgambit** [comment]
thanks, so you are saying that if my timestamps look like
`2014-01-01 20:05:05.12345678` I should be able to `nanotime()` them and then use in ggplot directly?

**Comment by eddelbuettel** [comment]
No, that was not what I said.

**Comment by randomgambit** [comment]
ha! sorry then, coming from Python I am not 100% familiar with all the terminology. I dont understand when you say `For POSIXct we get this for free because R natively supports, for extensions we have to do it by hand (and eventually integrate it)`
