### ISSUE TITLE
printing tibbles with nanotime

### ISSUE THREAD

**Issue by ijlyttle** [eddelbuettel/nanotime#31]
Hi,

I suspect that this issue falls in a grey area between nanotime and tibble.

I cannot get a tibble to print, but I can get a data.frame to print:

```
> tmp <- tibble::tibble(x = nanotime::nanotime(Sys.time()))
> tmp
Error in callNextMethod() : 
  error in evaluating a 'primitive' next method: Error in FUN(x = x, i = i) : could not find function "FUN"
> as.data.frame(tmp)
                                    x
1 2017-07-21T19:57:13.419241000+00:00
```

Is there something that nanotime can provide to be more "tibble-friendly"? My cursory google-search did not turn up anything.

As well, I have a problem to display in the RStudio viewer, but I'll take this one issue at a time ;)

FWIW, I am using CRAN versions of tibble and nanotime on R 3.4.1, using Linux.

**Comment by ijlyttle** [comment]
This seems relevant: https://github.com/tidyverse/tibble/issues/144

Still unclear to me how to proceed.

**Comment by joshuaulrich** [comment]
I don't see how this is a grey area.  nanotime is a fairly simple S4 class (~500 lines of R code) that wraps/extends an S3 class (integer64).  This is not an unconventional approach, and is described in Writing R Extensions.  Printing works fine for data.frame (as you show), and I believe it also works fine in data.table.  It obviously prints fine when not contained in any class.

The main unconventional component in your report is the tibble class.  I say it's unconventional because it explicitly breaks conventions its authors deem "bad".  It's also a bit much to ask other packages' to be "friendly" to a class that inherits from a class that has the expected behavior.  No matter how popular the class may be.

So, unless it's demonstrated that nanotime is doing something unreasonable, the responsibility for fixing the issue lies with the tibble class.

**Comment by eddelbuettel** [comment]
It works in a data.frame ... because we wrote dispatchers for it; first me as S3 and later @lsilvest for S4.

It works in data.table ... because @mattdowle is a nice guy who added explicit support for nanotime (on top of support for integer64 which he already had).  

For tibble, this is between you and the other tibblyverse folks.  If you want it, you may have to add it.  We can't push this up into them, particularly if they choose to ignore the proper formatters we have   So in short, @joshuaulrich is entirely correct here.

**Comment by ijlyttle** [comment]
Fair enough - I should have worded my initial post differently, the "grey area" may have existed only in my head. I should not have implied that the responsibility was nanotime's.

I will raise this on the tibble end, keeping my eyes open for potential solutions. 

I something promising appears, I could propose it here. Of course, I would be happy to make a PR, if this gets that far.

**Comment by eddelbuettel** [comment]
Yep, sounds good.  There is no reason why I cannot / should not work over with the tibblies, but we thing the change has to occur at our end as other data structure happily dispatch and format.

Should a need for change at our end arise we can probably make it.  Let's discuss if and when that need materializes.
